### ISSUE TITLE
module not found: org.lyranthe#fs2-mongodb_2.12;0.4.0

### ISSUE THREAD

**Issue by BalmungSan** [fiadliel/fs2-mongodb#3]
Hi, I know it was released only a few hours ago, but I was hopping to use the latest release. _(Specially for the removed deprecations in #2)_.

Did you miss the publish step?
Or are you planning to release it latter?

**Comment by eperinan** [comment]
I have been talking with @fiadliel and he has just republished it

It's working now. https://repo1.maven.org/maven2/org/lyranthe/fs2-mongodb_2.12/0.4.0/

Could you confirm that it is working fine for you?

**Comment by BalmungSan** [comment]
Hi, yes it is working now, thanks.
